import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("window");

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "linear-gradient(180deg, #dbeafe, #fff)", // fallback
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 15,
  },
  innerContainer: {
    width: width > 400 ? 380 : "100%",
    backgroundColor: "#ffffffcc",
    borderRadius: 32,
    paddingVertical: 45,
    paddingHorizontal: 30,
    alignItems: "center",
    shadowColor: "#3b82f6",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.1,
    shadowRadius: 25,
    elevation: 20,
    borderWidth: 1,
    borderColor: "#e0e7ff",
  },
  logoPillContainer: {
    width: 140,
    height: 70,
    borderRadius: 35,
    overflow: "hidden",
    backgroundColor: "#e0e7ff",
    marginBottom: 35,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#7dd3fc",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.6,
    shadowRadius: 12,
    elevation: 10,
  },
  logo: {
    width: 140,
    height: 70,
    borderRadius: 35,
    resizeMode: "cover",
  },
  title: {
    fontSize: 34,
    fontWeight: "800",
    color: "#1e3a8a",
    marginBottom: 28,
    letterSpacing: 0.5,
  },
  errorText: {
    color: "#dc2626",
    backgroundColor: "#fee2e2",
    padding: 12,
    borderRadius: 12,
    width: "100%",
    textAlign: "center",
    marginBottom: 20,
    fontSize: 15,
  },
  input: {
    width: "100%",
    backgroundColor: "#f8fafc",
    borderRadius: 16,
    paddingHorizontal: 20,
    paddingVertical: 14,
    color: "#1e3a8a",
    marginBottom: 18,
    fontSize: 17,
    borderWidth: 1,
    borderColor: "#dbeafe",
    shadowColor: "#dbeafe",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 5,
  },
  button: {
    backgroundColor: "#3b82f6",
    paddingVertical: 16,
    borderRadius: 20,
    alignItems: "center",
    width: "100%",
    shadowColor: "#2563eb",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.5,
    shadowRadius: 12,
    elevation: 12,
  },
  buttonText: {
    color: "#f0f9ff",
    fontSize: 20,
    fontWeight: "bold",
  },
  forgotText: {
    color: "#1e40af",
    fontSize: 14,
    marginTop: 25,
    marginBottom: 18,
    textDecorationLine: "underline",
  },
  signupText: {
    fontSize: 15,
    color: "#334155",
    textAlign: "center",
  },
  signupLink: {
    color: "#1e3a8a",
    fontWeight: "700",
  },
});

export default styles;
